/*****************************************************************************
 * XMClib v2.2.0 - XMC Peripheral Driver Library
 *
 * Copyright (c) 2015-2020, Infineon Technologies AG
 * All rights reserved.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * To improve the quality of the software, users are encouraged to share
 * modifications, enhancements or bug fixes with Infineon Technologies AG
 * at XMCSupport@infineon.com.
 *****************************************************************************
 * @file
 * @date 04 Dec, 2014
 * @version 1.0.0
 *
 * @brief XMC1100 Boot kit blinky GPIO demo example
 *
 * The blinky example flashes the leds of the board with a periodic rate.
 * LED1 is connected to P0.6
 *
 * History <br>
 *
 * Version 1.0.0 Initial <br>
 *
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <XMC1100.h>
#include <xmc_flash.h>
#include <xmc_gpio.h>
#include <xmc_rtc.h>
#include <xmc_scu.h>
#include <xmc_uart.h>

#include "lcd2004.h"
#include "led.h"
#include "lcd_pwm_vo.h"

#ifndef HZ
#define HZ 1000
#endif

#define UART_RX P1_3
#define UART_TX P1_2

XMC_GPIO_CONFIG_t uart_tx;
XMC_GPIO_CONFIG_t uart_rx;

__IO uint32_t g_Ticks;

/* UART configuration */
const XMC_UART_CH_CONFIG_t uart_config = {
    .data_bits = 8U, .stop_bits = 1U, .baudrate = 256000};

XMC_RTC_CONFIG_t rtc_config = {.time.seconds = 5U, .prescaler = 0x7fffU};

XMC_RTC_TIME_t init_rtc_time = {.year = 2018,
                                .month = XMC_RTC_MONTH_JANUARY,
                                .daysofweek = XMC_RTC_WEEKDAY_TUESDAY,
                                .days = 27,
                                .hours = 15,
                                .minutes = 40,
                                .seconds = 55};

uint8_t line[4][21] = {__DATE__, __TIME__, "Happy Spring Festvl", "               "};

void SystemCoreClockSetup(void) {
  XMC_SCU_CLOCK_CONFIG_t clock_config = {
      .rtc_src = XMC_SCU_CLOCK_RTCCLKSRC_DCO2,
      .pclk_src = XMC_SCU_CLOCK_PCLKSRC_DOUBLE_MCLK,
      .fdiv = 0,
      .idiv = 1};

  XMC_SCU_CLOCK_Init(&clock_config);

  //  SystemCoreClockUpdate();
}

static inline void SimpleDelay(uint32_t d) {
  uint32_t t = d;
  while (--t) {
    __NOP();
  }
}

void XMC_AssertHandler(const char *const msg, const char *const file,
                       uint32_t line) {
  printf("Assert:%s,%s,%u\n", msg, file, line);

  while (1) {
    LED_Toggle(1);
    SimpleDelay(100000);
  }
}

void SysTick_Handler(void) {
		g_Ticks++;
}

int main(void) {
  __IO uint32_t tmpTick;
  __IO uint32_t deltaTick;
  __IO uint32_t i = 0;

  __IO XMC_RTC_TIME_t now_rtc_time;

	SystemCoreClockSetup();
  /* System timer configuration */
  SysTick_Config(SystemCoreClock / HZ);
	
  /*Initialize the UART driver */
  uart_tx.mode = XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT7;
  uart_rx.mode = XMC_GPIO_MODE_INPUT_TRISTATE;
  /* Configure UART channel */
  XMC_UART_CH_Init(XMC_UART0_CH1, &uart_config);
  XMC_UART_CH_SetInputSource(XMC_UART0_CH1, XMC_UART_CH_INPUT_RXD,
                             USIC0_C1_DX0_P1_3);

  /* Start UART channel */
  XMC_UART_CH_Start(XMC_UART0_CH1);

  /* Configure pins */
  XMC_GPIO_Init(UART_TX, &uart_tx);
  XMC_GPIO_Init(UART_RX, &uart_rx);
	
#if defined(__ARMCC_VERSION)
	printf("ARMCC %u\n", __ARMCC_VERSION);
#endif

  printf("LCD2004 4bit mode For XMC1100 Bootkit. CM0 Rev:%u, %u Hz\n",
         __CM0_REV, SystemCoreClock);
  printf("CPUID:%08X, MPU:%u\n", SCB->CPUID, __MPU_PRESENT);
  // RTC
  XMC_RTC_Init(&rtc_config);
  XMC_RTC_SetTime(&init_rtc_time);

  //  XMC_RTC_EnableEvent(XMC_RTC_EVENT_PERIODIC_SECONDS);
  //  XMC_SCU_INTERRUPT_EnableEvent(XMC_SCU_INTERRUPT_EVENT_RTC_PERIODIC);
  //  NVIC_SetPriority(SCU_1_IRQn, 3);
  //  NVIC_EnableIRQ(SCU_1_IRQn);
  XMC_RTC_Start();
	
	LED_Initialize();
	
  LCD_Initialize();

  LCD_displayL(0, 0, line[0]);
  LCD_displayL(1, 0, line[1]);
  LCD_displayL(2, 0, line[2]);
  LCD_displayL(3, 0, line[3]);
	
	uint8_t g_line_buf[21] = {};
  while (1)
  {
    LED_On(0);

    tmpTick = g_Ticks;
    while ((tmpTick + (HZ)) > g_Ticks) {
      __NOP();
      __WFI();
    }

    XMC_RTC_GetTime((XMC_RTC_TIME_t *)&now_rtc_time);
		printf("%02d:%02d:%02d\n", now_rtc_time.hours, now_rtc_time.minutes, now_rtc_time.seconds);
		
		sprintf(g_line_buf, "%02d:%02d:%02d", now_rtc_time.hours, now_rtc_time.minutes, now_rtc_time.seconds);
		LCD_displayL(3, 0, g_line_buf);		
		
    LED_Off(0);

    tmpTick = g_Ticks;
    while ((tmpTick + (HZ)) > g_Ticks) {
      __NOP();
      __WFI();
    }
  }
}
