/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'gpio_toggle_xmc11' 
 * Target:  'gpio_toggle_xmc11' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "XMC1100.h"



#endif /* RTE_COMPONENTS_H */
